name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5000:5000
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set up database
      run: |
        sudo apt-get install libpq-dev
        source venv/bin/activate
        pip install psycopg2
        python -c "from app import db, create_app; app = create_app(); with app.app_context(): db.create_all()"

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --disable-warnings

    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a YOUR_HEROKU_APP
        git push heroku main